version: 1.0

###################################
# Essential configuration options #
###################################

genome:
    name: "{{cookiecutter.genome}}"
    fasta: "{{cookiecutter.fasta}}"
    fasta_index: "{{cookiecutter.fasta_index}}"
    indicies: "{{cookiecutter.indicies}}"
    chromosome_sizes: "{{cookiecutter.chromosome_sizes}}"

read_type: "{{cookiecutter.read_type}}"
shift_atac_reads: "no"
remove_blacklist: "{{cookiecutter.remove_blacklist}}"
call_snps: "{{cookiecutter.call_snps}}"
annotate_snps: "{{cookiecutter.annotate_snps}}"

make_bigwigs: "no"
make_ucsc_hub: "no"

###################################
#  Optional configuration         #
###################################

design: "design.csv"
blacklist: "{{cookiecutter.blacklist}}"
snp_database: "{{cookiecutter.snp_database}}"
remove_pcr_duplicates_method: "{{cookiecutter.remove_pcr_duplicates_method}}"

#################################
# Tool specific options         #
#################################

trim_galore:
    threads: 4
    options: 

bowtie2:
    threads: 4
    options:

picard:
    threads: 4
    options:
    
bcftools:
    threads: 4
    options: 
