version: 1.0

###################################
# Essential configuration options #
###################################

genome:
    name: "{{cookiecutter.genome}}"
    fasta: "{{cookiecutter.fasta}}"
    fasta_index: "{{cookiecutter.fasta_index}}"
    indicies: "{{cookiecutter.indicies}}"
    chromosome_sizes: "{{cookiecutter.chromosome_sizes}}"

read_type: "{{cookiecutter.read_type}}"
split_fastq: "{{cookiecutter.split_fastq}}"
split_fastq_parts: "{{cookiecutter.split_fastq_parts}}"
shift_atac_reads: "no"
remove_blacklist: "{{cookiecutter.remove_blacklist}}"
call_snps: "{{cookiecutter.call_snps}}"
annotate_snps: "{{cookiecutter.annotate_snps}}"

make_bigwigs: "no"

make_ucsc_hub: "{{cookiecutter.make_ucsc_hub}}"
ucsc_hub_details:
    directory: "{{cookiecutter.UCSC_hub_directory}}"
    name: "{{cookiecutter.project_name}}"
    short: "{{cookiecutter.project_name}}"
    long: "{{cookiecutter.project_name}}"
    email: "{{cookiecutter.email}}"
    color_by: "{{cookiecutter.color_by}}"

###################################
#  Optional configuration         #
###################################

design: "design.csv"
blacklist: "{{cookiecutter.blacklist}}"
snp_database: "{{cookiecutter.snp_database}}"
remove_pcr_duplicates_method: "{{cookiecutter.remove_pcr_duplicates_method}}"

#################################
# Tool specific options         #
#################################

trim_galore:
    threads: 4
    options: --2colour 20 

bowtie2:
    threads: 4
    options:

picard:
    threads: 4
    options:
    
bcftools:
    threads: 4
    options: 
