name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
- bcftools
- bedtools
- bowtie2
- deeptools
- fastq-screen
- fastqc
- fastqsplitter
- homer
- macs2
- multiqc
- numpy>=1.19
- picard-slim
- pip
- pysam
- python>=3.10
- samtools>1.7
- star
- salmon
- subread
- trackhub
- trim-galore
- ucsc-bedgraphtobigwig
- ucsc-bedtobigbed
- ucsc-bigbedtobed
- ucsc-fetchchromsizes