jobname: smk-{jobid}-{rule}-{wildcards}
drmaa: --cpus-per-task={threads} --mem={resources.mem_mb} * {threads} --time=0-8:00:00
use-singularity: true
singularity-args: -B /ceph -B /databank
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
latency-wait: 30
show-failed-logs: True
cores: 8
