version: 1.0

###################################
# Essential configuration options #
###################################

genome:
    name: "hg38"
    chromosome_sizes: "ngs_pipeline/data/resources/hg38/hg38.chrom.sizes"
    indicies: "/databank/igenomes/Homo_sapiens/UCSC/hg38/Sequence/Bowtie2Index/genome"

###################################
#  Optional configuration         #
###################################

design: "2023-01-29_newchip_test/samples_newchip_test.csv"
blacklist: "ngs_pipeline/data/resources/hg38/hg38-blacklist.v2.bed.gz"
pileup_method: "deeptools"
peak_calling_method: "macs"
remove_pcr_duplicates_method: "picard"

ucsc_hub_details:
    directory: "na"
    name: "na"
    short: "na"
    long: "na"
    email: "na"
    color_by: "antibody"

#################################
# Tool specific options         #
#################################

trim_galore:
    threads: 4

bowtie2:
    threads: 4
    options:

homer:
    use_input: true
    maketagdirectory:
    makebigwig:
    findpeaks:

deeptools:
    threads: 8
    alignmentsieve: --minMappingQuality 30 
    # Options passed to deeptools BamCoverage
    # These need to be replaced
    # e.g. --extendReads -bs 1 --normalizeUsing RPKM
    bamcoverage: --extendReads -bs 1 --normalizeUsing RPKM

macs:
    version: 2
    callpeak:

lanceotron:
    # Instructs lanceotron to use the matched input file for peak calling
    # No effect if input file is not matched
    use_input: True
    # Options passed to callPeaks[Input] command
    callpeak: -c 0.5

