executor: local
jobs: 100


use-conda: "False"
software-deployment-method: "apptainer"
use-apptainer: "True"

show-failed-logs: "True"
printshellcmds: "True"


default-resources: 
    slurm_partition: "short"
    runtime: "1h"
    mem: "3G"