__use_yte__: true
executor: slurm
jobs: 50

software-deployment-method: 
    - "apptainer"
use-apptainer: true
# apptainer-args: "-H $PWD"

show-failed-logs: true
printshellcmds: true


default-resources: 
    slurm_partition: "short"
    runtime: "1h"
    mem: "3G"

# local-storage-prefix: $TMPDIR
# default-storage-provider: fs
# shared-fs-usage:
#   - persistence
#   - software-deployment
#   - sources
#   - source-cache