################################
# Imports
################################
import os
import shutil
from seqnado.config import SeqnadoConfig
from seqnado.inputs import (
    SampleGroupings,
    SampleGroups,
    select_sample_collection,
)
from seqnado.outputs import SeqnadoOutputFactory, SeqnadoOutputFiles
from seqnado.helpers import remove_unwanted_run_files


################################
# Hardcoded Config
################################
SCALE_RESOURCES = float(os.environ.get("SCALE_RESOURCES", "1"))


container: "oras://ghcr.io/alsmith151/seqnado_pipeline:latest"


################################
# Load Configuration
################################
CONFIG = SeqnadoConfig(**config)  # pyright: ignore[reportUndefinedVariable]
ASSAY = CONFIG.assay
INPUT_FILES = select_sample_collection(ASSAY).from_csv(CONFIG.metadata)


################################
# Define Sample Groupings
################################
SAMPLE_GROUPINGS = SampleGroupings()

normalisation_groups = SampleGroups.from_dataframe(
    INPUT_FILES.to_dataframe(),
    subset_column="norm_group",
    include_controls=True,
)

scaling_groups = SampleGroups.from_dataframe(
    INPUT_FILES.to_dataframe(),
    subset_column="scaling_group",
    include_controls=True,
)

consensus_groups = SampleGroups.from_dataframe(
    INPUT_FILES.to_dataframe(),
    subset_column="consensus_group",
    include_controls=True,
)

SAMPLE_GROUPINGS.add_grouping("normalisation", normalisation_groups)
SAMPLE_GROUPINGS.add_grouping("scaling", scaling_groups)
SAMPLE_GROUPINGS.add_grouping("consensus", consensus_groups)


################################
# Define Outputs
################################
OUTPUTS: SeqnadoOutputFiles = (
    SeqnadoOutputFactory(
        assay=ASSAY,
        samples=INPUT_FILES,
        config=CONFIG,
        sample_groupings=SAMPLE_GROUPINGS,
    )
    .create_output_builder()
    .build()
)

SAMPLE_NAMES = OUTPUTS.sample_names


################################
# Set-Up Workflow
################################
INPUT_FILES.symlink_fastq_files(output_dir="seqnado_output/fastq/")


################################
# Include Rules
################################
include: "rules/common.smk"
include: "rules/align.smk"
include: "rules/alignment_post_processing.smk"
include: "rules/fastq_screen.smk"
include: "rules/fastq_trim.smk"
include: "rules/pileup_default.smk"
include: "rules/pileup_norm.smk"
include: "rules/pileup_grouped.smk"
include: "rules/peak_call_other.smk"
include: "rules/peak_call_grouped.smk"
include: "rules/qc.smk"
include: "rules/heatmap.smk"
include: "rules/hub.smk"
include: "rules/geo_submission.smk"
include: "rules/visualisation.smk"
include: "rules/consensus_counts.smk"
include: "rules/dataset.smk"
include: "rules/exogenous_norm.smk"
include: "rules/peak_call_chip.smk"
include: "rules/crispr.smk"


################################
# Rule Ordering
################################
if CONFIG.has_spikein:
    ruleorder: move_ref_bam > align_paired > align_single
    ruleorder: deeptools_make_bigwigs_spikein > deeptools_make_bigwigs
    ruleorder: align_paired_spikein > align_paired > align_single_spikein > align_single

else:
    ruleorder: align_paired > align_single > move_ref_bam
    ruleorder: align_paired > align_paired_spikein > align_single > align_single_spikein 


################################
# Final Aggregation Rule
################################
rule all:
    input:
        OUTPUTS.all_files,


################################
# Workflow Hooks
################################
onsuccess:
    remove_unwanted_run_files()


onerror:
    log_out = "seqnado_error.log"
    shutil.copyfile(log, log_out)  # pyright: ignore[reportUndefinedVariable]
    print(
        f"An error occurred. Please check the log file {log_out} for more information."
    )
    remove_unwanted_run_files()
